### PR TITLE
Fixed ThreeWay Intersections

### PR DESCRIPTION
**Pull request by Sky4Flowers**
Contains:
- Corrected sign/trafic light placing
- Removed weird shoulder bug

Case:
End of spline is connected with a middle node of own spline

Error0
Error0_Fixed

### CODE REVIEW

**Comment by FritzsHero** [comment]
Hello !

Thanks for your contribution.
I'll look into it and do my testing.


Best Regards

Fritzs

**Comment by FritzsHero** [comment]
Hey,

I looked at it and it works without breaking my tests.
However I have some things you should/could improve in the future.

1. You changed the line spacing, resulting in more commited lines then you changed. You used tabs instead of space, git does handle this poorly.
2. The name of the commiter is different then your username, but it has not to be the same.
3. You didn't use an Email adress in your commit. This is a problem, you can use the anonym email adress, provided by Github in your settings, if you want to hide your real email. Your commit will still be linked with your account when you use this anonymized adress.

You can overwrite your commit and push again.
If you have any questions, just get back to me.


Thanks

Fritzs

**Comment by Sky4Flowers** [comment]
Hey Fritz,

Sorry for the line spacing changes. They are caused by the auto-formatting of my IDE. I will try to remove those changes in future commits.
The new commit should be correct. If there are any issues left feel free to contact me.

Thanks for your feedback and for continuing this great project!

Crea

**Comment by FritzsHero** [comment]
Now I got the time to finally incorporate your changes.
Used Squash merge.

Again, thank you for your contribution.


Best Regards

Fritzs

**Pull request merged**
